FROM alpine:3.6
WORKDIR /app
VOLUME /app
RUN apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    rm -r /root/.cache
RUN python3 -m pip install --upgrade google-assistant-sdk && \
python3 -m pip install --upgrade google-auth-oauthlib[tool] && \
python3 -m google-oauthlib-tool --client-secrets app/client_secret.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless
